apiVersion: kafka.strimzi.io/v1  # Updated
kind: Kafka
metadata:
  name: recovery-kafka
  namespace: kafka
spec:
  kafka:
    replicas: 1
    version: 3.7.0
...
---
apiVersion: kafka.strimzi.io/v1  # Updated here as well
kind: KafkaTopic
metadata:
  name: recovery-events
  namespace: kafka
  labels:
    strimzi.io/cluster: recovery-kafka
spec:
  partitions: 3
  replicas: 1
...