apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - role.yaml
  - clusterrolebinding.yaml
  - leader-election-role.yaml
  - rolebinding.yaml
  - sparkapplication_viewer_role.yaml
  - sparkapplication_editor_role.yaml
  - scheduledsparkapplication_viewer_role.yaml
  - scheduledsparkapplication_editor_role.yaml
