apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-stack
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - app: prometheus
            chart: kube-prometheus-stack
            repoURL: https://prometheus-community.github.io/helm-charts
            targetRevision: 58.0.0
            namespace: observability

          - app: grafana
            chart: grafana
            repoURL: https://grafana.github.io/helm-charts
            targetRevision: 7.3.7
            namespace: observability

          - app: loki
            chart: loki
            repoURL: https://grafana.github.io/helm-charts
            targetRevision: 6.25.0
            namespace: observability

          - app: tempo
            chart: tempo
            repoURL: https://grafana.github.io/helm-charts
            targetRevision: 1.10.1
            namespace: observability

  template:
    metadata:
      name: "{{app}}"
    spec:
      project: default

      sources:
        # Source 1: Helm chart from chart museum
        - repoURL: "{{repoURL}}"
          chart: "{{chart}}"
          targetRevision: "{{targetRevision}}"
          helm:
            valueFiles:
              - $values/infra/observability/{{app}}/values.yaml

        # Source 2: Your git repo holding the values files
        - repoURL: https://github.com/Sanchar127/HAADE.git
          targetRevision: sanchar-dev
          ref: values

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true