apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingestion
  namespace: observability
  labels:
    release: prometheus   
spec:
  selector:
    matchLabels:
      app: ingestion

  namespaceSelector:
    matchNames:
      - recovery

  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s