apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-service.yaml
  - ingestion-deployment.yaml
  - ingestion-service.yaml
  - ingestion-servicemonitor.yaml
  - trend-consumer-deployment.yaml
  - consumer/service.yaml
  - consumer/servicemonitor.yaml
  - ingress.yaml
