apiVersion: skaffold/v2beta29
kind: Config

build:
  artifacts:
    - image: sanchar127/ingestion-service
      context: .
      docker:
        dockerfile: infra/docker/ingestion/Dockerfile

    - image: sanchar127/trend-consumer-service
      context: .
      docker:
        dockerfile: infra/docker/consumer/trend-consumer/Dockerfile

deploy:
  kubectl:
    manifests:
      # =========================
      # BASE INFRA (CONFIG + SECRETS)
      # =========================
      - infra/k8s/base/configmap.yaml
      - infra/k8s/base/secrets.yaml

      # =========================
      # APPLICATION LAYER
      # =========================
      - infra/k8s/apps/*.yaml

      # =========================
      # LAKEHOUSE STORAGE LAYER
      # =========================
      - infra/k8s/lakehouse/storage/*.yaml
      - infra/k8s/lakehouse/minio/*.yaml

      # =========================
      # LAKEHOUSE PROCESSING
      # =========================
      - infra/k8s/lakehouse/iceberg/*.yaml
      - infra/k8s/lakehouse/spark/*.yaml

portForward:
  - resourceType: deployment
    resourceName: ingestion
    namespace: recovery
    port: 8001
    localPort: 8001

  - resourceType: deployment
    resourceName: trend-consumer
    namespace: recovery
    port: 8081
    localPort: 8081