apiVersion: skaffold/v2beta29
kind: Config

build:
  artifacts:
    - image: ingestion-service
      context: .
      docker:
        dockerfile: infra/docker/ingestion/Dockerfile

  local:
    push: false

deploy:
  kubectl:
    manifests:
      - infra/k8s/base/*.yaml
      - infra/k8s/apps/*.yaml
      - infra/k8s/kafka/*.yaml