apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  - bases/sparkoperator.k8s.io_sparkapplications.yaml
  - bases/sparkoperator.k8s.io_sparkconnects.yaml

patches:
  - path: patches/webhook_in_sparkapplications.yaml
  - path: patches/webhook_in_scheduledsparkapplications.yaml
  - path: patches/webhook_in_sparkconnects.yaml

configurations:
  - kustomizeconfig.yaml
