admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password

persistence:
  enabled: true
  size: 20Gi

service:
  type: ClusterIP

datasources:
  datasources.yaml:
    apiVersion: 1

    datasources:

      - name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://monitoring-kube-prometheus-prometheus:9090

      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1

    providers:
      - name: default
        folder: General
        type: file
        disableDeletion: false
        editable: true

        options:
          path: /var/lib/grafana/dashboards