apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trend-consumer
  namespace: observability
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: trend-consumer

  namespaceSelector:
    matchNames:
      - recovery

  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s