apiVersion: v1
kind: Secret
metadata:
  name: polaris-persistence
  namespace: polaris
type: Opaque
stringData:
  username: polaris
  password: "postgres"
  jdbcUrl: "jdbc:postgresql://postgres.recovery.svc.cluster.local:5432/polaris"