apiVersion: v1
kind: ConfigMap
metadata:
  name: iceberg-config
  namespace: spark
  labels:
    app.kubernetes.io/name: iceberg
    app.kubernetes.io/component: catalog-client
data:
  catalog.properties: |
    type=rest
    uri=http://polaris.polaris.svc.cluster.local:8181/api/catalog
    warehouse=warehouse