apiVersion: v1
kind: ConfigMap
metadata:
  name: recovery-config
  namespace: recovery
data:
  KAFKA_BOOTSTRAP_SERVERS: recovery-cluster-kafka-bootstrap.kafka:9092
  KAFKA_TOPIC: recovery-events
  RETRY_TOPIC: recovery-events-retry
  DLQ_TOPIC: recovery-events-dlq

  POSTGRES_HOST: postgres
  POSTGRES_DB: recovery
