apiVersion: v1
kind: Service
metadata:
  name: spark-metrics
  namespace: recovery
  labels:
    spark-role: driver
spec:
  selector:
    spark-role: driver
  ports:
    - name: metrics
      port: 8090
      targetPort: 8090