apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: lakehouse
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc
          command: ["/bin/sh", "-c"]
          args:
            - |
              until mc alias set local http://minio.lakehouse.svc.cluster.local:9000 minio minio123; do
                echo "waiting for minio..."
                sleep 5
              done
              mc mb -p local/warehouse || true
              mc mb -p local/iceberg || true
              mc mb -p local/loki || true
              mc ls local
